In [ ]:
import pandas as pd

## The training data for 'Is the Ad a Good Match to the Search Term' is given. It consists of 15 training instances. That means there are 15 rows. This dataset is small for a machine learning task. However, another dataset will be added during the qualification.

In [ ]:
df= pd.read_csv('taac_assistant_taac_3.csv')

In [ ]:
df.head()

TaskId         User_Search_Term  \
0       1     wwww ncquickpass com   
1       2         peloton plano tx   
2       3          antelope canyon   
3       4  get vaccine after covid   
4       5  ahs.com/my-accountlogin   

                                                  Ad  \
0               Nc Quick Pass - Pay Your Bill Online   
1  Studio Cycle Comparison - Find The Best Exerci...   
2  Hotels near Antelope Canyon - 100% Real Custom...   
3  Janssen COVID-19 Vaccine - Authorized For Emer...   
4  Find First american home warranty login - Chec...   

                                         Website Relevance  
0                 www.doxo.com/pay/nc-quick-pass     Other  
1         www.nordictrack.com/Studio-Cycles/S22i     Other  
2         www.booking.com/Antelope-Canyon/Hotels     Other  
3                  www.janssencovid19vaccine.com     Other  
4  www.searchandshopping.org/Your Search/Results     Other

In [ ]:
#Converting the Relevance to numerical values to enable analysis
#Convert Relevance to numerical
mapping = {
    'Good' : 1,
    'Other' : 0,
}
df['Relevance'] = df['Relevance'].replace(mapping)
df.head(10)

TaskId          User_Search_Term  \
0       1      wwww ncquickpass com   
1       2          peloton plano tx   
2       3           antelope canyon   
3       4   get vaccine after covid   
4       5   ahs.com/my-accountlogin   
5       6                      nike   
6       7               cfl fixture   
7       8  nationwide pet insurance   
8       9                      nike   
9      10                 used cars   

                                                  Ad  \
0               Nc Quick Pass - Pay Your Bill Online   
1  Studio Cycle Comparison - Find The Best Exerci...   
2  Hotels near Antelope Canyon - 100% Real Custom...   
3  Janssen COVID-19 Vaccine - Authorized For Emer...   
4  Find First american home warranty login - Chec...   
5  Shop Womens Shops: Amazon - Amazon.com Officia...   
6                             Flashlight Accessories   
7  2021's Top 10 Pet Insurance - Buyer's Guide (N...   
8  Nike Official Site - Just Do It - Shop The Lat...   
9  CarMax Used Cars - Visit carmax.com - Large Na...   

                                         Website  Relevance  
0                 www.doxo.com/pay/nc-quick-pass          0  
1         www.nordictrack.com/Studio-Cycles/S22i          0  
2         www.booking.com/Antelope-Canyon/Hotels          0  
3                  www.janssencovid19vaccine.com          0  
4  www.searchandshopping.org/Your Search/Results          0  
5            www.amazon.com/apparel/womens-shops          1  
6                   www.Grainfer.com/Flashlights          0  
7                  buyersguide.org/Pet-Insurance          1  
8                                   www.nike.com          1  
9                            www.carmax.com/cars          1

In [ ]:
#df.isna().value_counts()
# Check for missing values
df.isnull().sum().any()

False

In [ ]:
# Identify rows with missing values
rows_with_missing_values = df[df.isnull().any(axis=1)]

# Print the rows with missing values
print("Rows with missing values:")
print(rows_with_missing_values)

Rows with missing values:
Empty DataFrame
Columns: [TaskId, User_Search_Term, Ad, Website, Relevance]
Index: []


In [ ]:
## Get the Independent Features

X=df.drop(columns =['TaskId', 'Relevance'])

In [ ]:
## Get the Dependent features
y=df['Relevance']

In [ ]:
y.value_counts()

1    130
0    108
Name: Relevance, dtype: int64

In [ ]:
#It can be seen that the data is generally balanced

In [ ]:
X.shape

(238, 3)

In [ ]:
y.shape

(238,)

In [ ]:
pip install --upgrade tensorflow

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 489.8/489.8 MB 1.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 55.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 8.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 71.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.7/440.7 kB 35.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 76.9 MB/s eta 0:00:00
  Attempting uninstall: wrapt
    Found existing installation: wrapt 1.15.0
    Uninstalling wrapt-1.15.0:
      Successfully uninstalled wrapt-1.15.0
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.13.0
    Uninstalling tensorflow-estimator-2.13.0:
      Successfully uninstalled tensorflow-estimator-2.13.0
  Attempting uninstall: ml-dtypes
    Found existing installation: ml-dtypes 0.3.1
    Uninstalling ml-dtypes-0.3.1:
      Successfully uninstalled ml-dtypes-0

In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.14.0'

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout

In [ ]:
### Vocabulary size
voc_size=10

Onehot Representation

In [ ]:
messages=X.copy()

In [ ]:
messages['User_Search_Term'][1]

'peloton plano tx'

In [ ]:
messages['Ad'][1]

'Studio Cycle Comparison - Find The Best Exercise Bike - NordicTrack Official Site'

In [ ]:
messages.reset_index(inplace=True)

In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['User_Search_Term'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237


In [ ]:
corpus

['wwww ncquickpass com',
 'peloton plano tx',
 'antelop canyon',
 'get vaccin covid',
 'ah com accountlogin',
 'nike',
 'cfl fixtur',
 'nationwid pet insur',
 'nike',
 'use car',
 'car rental lubbock tx',
 'augusta tech adn',
 'hampton inn guntersvil al',
 'white strip',
 'florist laguna beach',
 'rachel ray nylon spoon',
 'dental mouthwash fix teeth',
 'june florist brooklyn',
 'buy marbl floor tile',
 'safeway com',
 'enterpris rent car',
 'flight atlanta fort sill ok',
 'virgin',
 'adob clean',
 'dialysi clinic hire near',
 'best place sell old playboy magazin',
 'comput viru',
 'hepat b',
 'social secur administr',
 'goldman sach platinum',
 'homegood com offici websit',
 'madam pompadour wallpap mural',
 'southwest airlin',
 'cowboy schedul',
 'realmushroom',
 'abbotsford hear center',
 'amazon',
 'aliana health',
 'bilater maxilari sinu diseas',
 'first time homebuy',
 'norton vpn',
 'world educ servic',
 'new ford f regular cab sale near',
 'creat weekli payrol calendar',
 'arch

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[8, 5, 3],
 [7, 3, 3],
 [4, 8],
 [6, 2, 1],
 [2, 3, 2],
 [4],
 [7, 6],
 [6, 6, 2],
 [4],
 [2, 8],
 [8, 1, 1, 3],
 [4, 3, 1],
 [8, 7, 3, 3],
 [5, 8],
 [5, 2, 2],
 [7, 4, 9, 8],
 [6, 2, 9, 9],
 [2, 5, 1],
 [3, 6, 8, 5],
 [6, 3],
 [3, 1, 8],
 [3, 3, 9, 2, 4],
 [3],
 [8, 6],
 [2, 2, 5, 2],
 [8, 2, 6, 9, 8, 5],
 [4, 8],
 [5, 4],
 [1, 4, 9],
 [4, 2, 2],
 [1, 3, 4, 3],
 [9, 7, 4, 3],
 [7, 4],
 [8, 6],
 [4],
 [8, 3, 8],
 [5],
 [6, 8],
 [6, 1, 5, 8],
 [8, 7, 7],
 [9, 3],
 [4, 2, 8],
 [8, 7, 8, 7, 9, 3, 2],
 [3, 3, 4, 1],
 [8, 6],
 [7, 4, 2, 8, 6],
 [8, 7, 5],
 [3, 1, 8],
 [3, 1, 5, 3],
 [2, 9, 6, 8],
 [8, 2, 5, 8],
 [8, 9, 7, 3, 1],
 [5, 8, 3, 7, 1],
 [7, 6, 5, 8],
 [4],
 [7, 2, 9],
 [8, 7, 3, 9],
 [7, 3, 3],
 [8, 3, 5, 5],
 [2, 7, 9],
 [2, 4],
 [5, 4],
 [4, 3, 8, 6, 7],
 [3, 8, 1, 8, 9, 5],
 [9, 3, 6, 9],
 [1, 5, 5],
 [1, 1, 2],
 [6, 7, 8],
 [7, 4],
 [2, 3],
 [3, 1, 4, 2],
 [2, 5, 7],
 [3, 4, 2, 1, 8],
 [8, 5, 4],
 [3, 1, 8],
 [8, 9, 2, 2, 7],
 [6, 7, 1, 8],
 [2, 4],
 [8, 4, 1, 8],
 [9, 3],
 

Embedding Representation

In [ ]:
sent_length=10
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[0 0 0 ... 8 5 3]
 [0 0 0 ... 7 3 3]
 [0 0 0 ... 0 4 8]
 ...
 [0 0 0 ... 4 1 4]
 [0 0 0 ... 3 7 6]
 [0 0 0 ... 2 9 2]]


In [ ]:
embedded_docs[0]

array([0, 0, 0, 0, 0, 0, 0, 8, 5, 3], dtype=int32)

In [ ]:
## Creating model
embedding_vector_features=10
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(25))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 10, 10)            100       
                                                                 
 lstm (LSTM)                 (None, 25)                3600      
                                                                 
 dense (Dense)               (None, 1)                 26        
                                                                 
Total params: 3726 (14.55 KB)
Trainable params: 3726 (14.55 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [ ]:
## Creating model
embedding_vector_features=10
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model1.add(Bidirectional(LSTM(25)))
model1.add(Dropout(0.7))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 10, 10)            100       
                                                                 
 bidirectional (Bidirection  (None, 50)                7200      
 al)                                                             
                                                                 
 dropout (Dropout)           (None, 50)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 51        
                                                                 
Total params: 7351 (28.71 KB)
Trainable params: 7351 (28.71 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [ ]:
len(embedded_docs),y.shape

(238, (238,))

In [ ]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [ ]:
X_final.shape,y_final.shape

((238, 10), (238,))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

Model Training

In [ ]:
### Finally Training
model1.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=16)

Epoch 1/10
10/10 [==============================] - 12s 534ms/step - loss: 0.6915 - accuracy: 0.5849 - val_loss: 0.6936 - val_accuracy: 0.5063
Epoch 2/10
10/10 [==============================] - 1s 53ms/step - loss: 0.6855 - accuracy: 0.5786 - val_loss: 0.6940 - val_accuracy: 0.5063
Epoch 3/10
10/10 [==============================] - 1s 64ms/step - loss: 0.6869 - accuracy: 0.5597 - val_loss: 0.6946 - val_accuracy: 0.5063
Epoch 4/10
10/10 [==============================] - 1s 70ms/step - loss: 0.6889 - accuracy: 0.5723 - val_loss: 0.6954 - val_accuracy: 0.5063
Epoch 5/10
10/10 [==============================] - 0s 41ms/step - loss: 0.6830 - accuracy: 0.5912 - val_loss: 0.6967 - val_accuracy: 0.5063
Epoch 6/10
10/10 [==============================] - 0s 40ms/step - loss: 0.6762 - accuracy: 0.5660 - val_loss: 0.6976 - val_accuracy: 0.5063
Epoch 7/10
10/10 [==============================] - 0s 34ms/step - loss: 0.6815 - accuracy: 0.5723 - val_loss: 0.6992 - val_accuracy: 0.5063
Epoch 8/10


Performance Metrics And Accuracy

In [ ]:
y_pred1 = np.argmax(model1.predict(X_test),axis=1)

3/3 [==============================] - 2s 8ms/step


In [ ]:
y_pred1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_test,y_pred1)

array([[39,  0],
       [40,  0]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred1)

0.4936708860759494

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.49      1.00      0.66        39
           1       0.00      0.00      0.00        40

    accuracy                           0.49        79
   macro avg       0.25      0.50      0.33        79
weighted avg       0.24      0.49      0.33        79



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
def predict_rel(predict_relevance):
    concatenated_text = ' '.join(predict_relevance)
    onehot_reprr = [one_hot(concatenated_text.lower(), voc_size)]
    padded = pad_sequences(onehot_reprr, maxlen=sent_length, padding='pre')
    return model1.predict(padded)

predict_relevance = ["nike", "Shop Womens Shops: Amazon - Amazon.com Officia...", "www.amazon.com/apparel/womens-shops"]
predicted_score = predict_rel(predict_relevance)


1/1 [==============================] - 0s 81ms/step


In [ ]:
predicted_score

array([[0.541256]], dtype=float32)

In [ ]:
pip install streamlit

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 17.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.0/190.0 kB 15.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 44.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.1/82.1 kB 4.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 4.7 MB/s eta 0:00:00


In [ ]:
import streamlit as st

Saving The Trained Model

In [ ]:
# Assuming 'model' is your trained Keras model
model.save('trained_model.h5')


/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [ ]:
pip install keras


In [ ]:
from keras.models import load_model

# Provide the correct file path to your saved model
model_filepath = 'trained_model.h5'

# Load the saved model
loaded_model = load_model(model_filepath)


In [ ]:
# Load the saved model
#with open('trained_model.h5', 'rb') as model_file:
    #loaded_model = load_model(model_file)

# Define the text data you want to predict
predict_relevance = ['Car shuttle from ann arbor to DTW', 'Book Airport Service Now - Top airport Car Service - Hassle-Free Airport Rides', 'limoinmiami.com/Miami Airport/Car Service']

# Call the predict_rel function using the loaded model
predicted_score = predict_rel(predict_relevance)
print(predicted_score)


1/1 [==============================] - 0s 58ms/step
[[0.5408209]]
